<a href="https://colab.research.google.com/github/cleifton/Data_Science/blob/master/Pre%C3%A7o%20a%C3%A7%C3%A3o%20Petr4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
import pandas as pd 
import yfinance as yf 
import plotly.express as px
import plotly.io as pio

In [33]:
pio.renderers.default = "svg"

In [34]:
df = yf.Ticker('PETR4.SA')
petr4 = df.history(period='10y')
petr4

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2013-01-02 00:00:00-02:00,8.104965,8.194164,7.983330,7.983330,30182600,0.0,0.0
2013-01-03 00:00:00-02:00,8.031985,8.271201,7.987386,8.271201,30552600,0.0,0.0
2013-01-04 00:00:00-02:00,8.242821,8.360402,8.177949,8.283366,36141000,0.0,0.0
2013-01-07 00:00:00-02:00,8.303637,8.380673,8.088748,8.141457,28069600,0.0,0.0
2013-01-08 00:00:00-02:00,8.153621,8.202275,7.890077,7.906296,29091300,0.0,0.0
...,...,...,...,...,...,...,...
2022-12-23 00:00:00-03:00,24.129999,25.219999,24.129999,25.120001,68387900,0.0,0.0
2022-12-26 00:00:00-03:00,25.120001,25.299999,24.820000,24.940001,28765200,0.0,0.0
2022-12-27 00:00:00-03:00,25.250000,25.309999,24.549999,25.110001,50803200,0.0,0.0
2022-12-28 00:00:00-03:00,25.100000,25.320000,24.750000,24.799999,57293500,0.0,0.0
2022-12-29 00:00:00-03:00,24.990000,25.049999,24.430000,24.500000,57901800,0.0,0.0

In [35]:
petr4 = petr4.drop(['Dividends','Stock Splits'], axis=1)
petr4

,Open,High,Low,Close,Volume
Date,,,,,
2013-01-02 00:00:00-02:00,8.104965,8.194164,7.983330,7.983330,30182600
2013-01-03 00:00:00-02:00,8.031985,8.271201,7.987386,8.271201,30552600
2013-01-04 00:00:00-02:00,8.242821,8.360402,8.177949,8.283366,36141000
2013-01-07 00:00:00-02:00,8.303637,8.380673,8.088748,8.141457,28069600
2013-01-08 00:00:00-02:00,8.153621,8.202275,7.890077,7.906296,29091300
...,...,...,...,...,...
2022-12-23 00:00:00-03:00,24.129999,25.219999,24.129999,25.120001,68387900
2022-12-26 00:00:00-03:00,25.120001,25.299999,24.820000,24.940001,28765200
2022-12-27 00:00:00-03:00,25.250000,25.309999,24.549999,25.110001,50803200
2022-12-28 00:00:00-03:00,25.100000,25.320000,24.750000,24.799999,57293500
2022-12-29 00:00:00-03:00,24.990000,25.049999,24.430000,24.500000,57901800

In [37]:
petr4['SMA9'] = petr4.Close.rolling(window=7).mean().round(2)
petr4['SMA21'] = petr4.Close.rolling(window=30).mean().round(2)
petr4

,Open,High,Low,Close,Volume,SMA7,SMA30,SMA9,SMA21
Date,,,,,,,,,
2013-01-02 00:00:00-02:00,8.104965,8.194164,7.983330,7.983330,30182600,NaN,NaN,NaN,NaN
2013-01-03 00:00:00-02:00,8.031985,8.271201,7.987386,8.271201,30552600,NaN,NaN,NaN,NaN
2013-01-04 00:00:00-02:00,8.242821,8.360402,8.177949,8.283366,36141000,NaN,NaN,NaN,NaN
2013-01-07 00:00:00-02:00,8.303637,8.380673,8.088748,8.141457,28069600,NaN,NaN,NaN,NaN
2013-01-08 00:00:00-02:00,8.153621,8.202275,7.890077,7.906296,29091300,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
2022-12-23 00:00:00-03:00,24.129999,25.219999,24.129999,25.120001,68387900,23.17,24.07,23.17,24.07
2022-12-26 00:00:00-03:00,25.120001,25.299999,24.820000,24.940001,28765200,23.59,24.11,23.59,24.11
2022-12-27 00:00:00-03:00,25.250000,25.309999,24.549999,25.110001,50803200,24.03,24.14,24.03,24.14
2022-12-28 00:00:00-03:00,25.100000,25.320000,24.750000,24.799999,57293500,24.37,24.17,24.37,24.17
2022-12-29 00:00:00-03:00,24.990000,25.049999,24.430000,24.500000,57901800,24.58,24.20,24.58,24.20

In [38]:
petr4_predict = petr4.tail(253)
petr4_predict

,Open,High,Low,Close,Volume,SMA7,SMA30,SMA9,SMA21
Date,,,,,,,,,
2021-12-28 00:00:00-03:00,16.953554,17.111343,16.772389,16.819141,30688100,16.64,15.96,16.64,15.96
2021-12-29 00:00:00-03:00,16.772389,16.889269,16.608756,16.678885,35508400,16.61,16.04,16.61,16.04
2021-12-30 00:00:00-03:00,16.684727,16.772388,16.591222,16.626287,43229100,16.63,16.14,16.63,16.14
2022-01-03 00:00:00-03:00,16.678885,17.076279,16.673041,17.000307,52704700,16.71,16.24,16.71,16.24
2022-01-04 00:00:00-03:00,17.041214,17.181471,16.895113,17.064590,51739200,16.79,16.36,16.79,16.36
...,...,...,...,...,...,...,...,...,...
2022-12-23 00:00:00-03:00,24.129999,25.219999,24.129999,25.120001,68387900,23.17,24.07,23.17,24.07
2022-12-26 00:00:00-03:00,25.120001,25.299999,24.820000,24.940001,28765200,23.59,24.11,23.59,24.11
2022-12-27 00:00:00-03:00,25.250000,25.309999,24.549999,25.110001,50803200,24.03,24.14,24.03,24.14
2022-12-28 00:00:00-03:00,25.100000,25.320000,24.750000,24.799999,57293500,24.37,24.17,24.37,24.17
2022-12-29 00:00:00-03:00,24.990000,25.049999,24.430000,24.500000,57901800,24.58,24.20,24.58,24.20

In [39]:
petr4.drop(petr4.tail(253).index, inplace=True)
petr4

,Open,High,Low,Close,Volume,SMA7,SMA30,SMA9,SMA21
Date,,,,,,,,,
2013-01-02 00:00:00-02:00,8.104965,8.194164,7.983330,7.983330,30182600,NaN,NaN,NaN,NaN
2013-01-03 00:00:00-02:00,8.031985,8.271201,7.987386,8.271201,30552600,NaN,NaN,NaN,NaN
2013-01-04 00:00:00-02:00,8.242821,8.360402,8.177949,8.283366,36141000,NaN,NaN,NaN,NaN
2013-01-07 00:00:00-02:00,8.303637,8.380673,8.088748,8.141457,28069600,NaN,NaN,NaN,NaN
2013-01-08 00:00:00-02:00,8.153621,8.202275,7.890077,7.906296,29091300,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
2021-12-20 00:00:00-03:00,16.620443,16.684727,16.176296,16.456810,106282500,17.06,15.49,17.06,15.49
2021-12-21 00:00:00-03:00,16.684727,16.784076,16.433434,16.480186,40454500,16.94,15.59,16.94,15.59
2021-12-22 00:00:00-03:00,16.597067,16.597067,16.345773,16.456810,33734500,16.83,15.67,16.83,15.67
2021-12-23 00:00:00-03:00,16.556160,16.608756,16.450967,16.556160,28713600,16.77,15.77,16.77,15.77
2021-12-27 00:00:00-03:00,16.550315,16.819142,16.450967,16.801609,44227900,16.72,15.87,16.72,15.87

In [40]:
petr4.dropna(inplace=True)
petr4

,Open,High,Low,Close,Volume,SMA7,SMA30,SMA9,SMA21
Date,,,,,,,,,
2013-02-15 00:00:00-02:00,7.139995,7.212976,7.107559,7.148103,25001600,7.18,7.72,7.18,7.72
2013-02-18 00:00:00-03:00,7.152157,7.277848,7.103503,7.257575,20291600,7.17,7.70,7.17,7.70
2013-02-19 00:00:00-03:00,7.261628,7.371100,7.253519,7.338664,28822000,7.20,7.67,7.20,7.67
2013-02-20 00:00:00-03:00,7.338664,7.338664,7.115666,7.144048,25939500,7.21,7.63,7.21,7.63
2013-02-21 00:00:00-03:00,7.083231,7.123776,6.973760,7.022413,30382300,7.18,7.59,7.18,7.59
...,...,...,...,...,...,...,...,...,...
2021-12-20 00:00:00-03:00,16.620443,16.684727,16.176296,16.456810,106282500,17.06,15.49,17.06,15.49
2021-12-21 00:00:00-03:00,16.684727,16.784076,16.433434,16.480186,40454500,16.94,15.59,16.94,15.59
2021-12-22 00:00:00-03:00,16.597067,16.597067,16.345773,16.456810,33734500,16.83,15.67,16.83,15.67
2021-12-23 00:00:00-03:00,16.556160,16.608756,16.450967,16.556160,28713600,16.77,15.77,16.77,15.77
2021-12-27 00:00:00-03:00,16.550315,16.819142,16.450967,16.801609,44227900,16.72,15.87,16.72,15.87

In [41]:
petr4.reset_index(drop=True, inplace=True)
petr4_predict.reset_index(drop=True, inplace=True)

In [42]:
petr4

,Open,High,Low,Close,Volume,SMA7,SMA30,SMA9,SMA21
0,7.139995,7.212976,7.107559,7.148103,25001600,7.18,7.72,7.18,7.72
1,7.152157,7.277848,7.103503,7.257575,20291600,7.17,7.70,7.17,7.70
2,7.261628,7.371100,7.253519,7.338664,28822000,7.20,7.67,7.20,7.67
3,7.338664,7.338664,7.115666,7.144048,25939500,7.21,7.63,7.21,7.63
4,7.083231,7.123776,6.973760,7.022413,30382300,7.18,7.59,7.18,7.59
...,...,...,...,...,...,...,...,...,...
2197,16.620443,16.684727,16.176296,16.456810,106282500,17.06,15.49,17.06,15.49
2198,16.684727,16.784076,16.433434,16.480186,40454500,16.94,15.59,16.94,15.59
2199,16.597067,16.597067,16.345773,16.456810,33734500,16.83,15.67,16.83,15.67
2200,16.556160,16.608756,16.450967,16.556160,28713600,16.77,15.77,16.77,15.77
2201,16.550315,16.819142,16.450967,16.801609,44227900,16.72,15.87,16.72,15.87

In [43]:
petr4.corr()

,Open,High,Low,Close,Volume,SMA7,SMA30,SMA9,SMA21
Open,1.000000,0.999329,0.999131,0.998396,0.147132,0.995897,0.969504,0.995897,0.969504
High,0.999329,1.000000,0.998905,0.999169,0.159619,0.995711,0.970129,0.995711,0.970129
Low,0.999131,0.998905,1.000000,0.999258,0.131804,0.994596,0.966664,0.994596,0.966664
Close,0.998396,0.999169,0.999258,1.000000,0.145099,0.994505,0.967585,0.994505,0.967585
Volume,0.147132,0.159619,0.131804,0.145099,1.000000,0.160585,0.189431,0.160585,0.189431
SMA7,0.995897,0.995711,0.994596,0.994505,0.160585,1.000000,0.979206,1.000000,0.979206
SMA30,0.969504,0.970129,0.966664,0.967585,0.189431,0.979206,1.000000,0.979206,1.000000
SMA9,0.995897,0.995711,0.994596,0.994505,0.160585,1.000000,0.979206,1.000000,0.979206
SMA21,0.969504,0.970129,0.966664,0.967585,0.189431,0.979206,1.000000,0.979206,1.000000

In [46]:
pip install pycaret

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting pycaret
  Downloading pycaret-2.3.10-py3-none-any.whl (320 kB)
     |████████████████████████████████| 320 kB 5.5 MB/s
Requirement already satisfied: cufflinks>=0.17.0 in /usr/local/lib/python3.8/dist-packages (from pycaret) (0.17.3)
Requirement already satisfied: wordcloud in /usr/local/lib/python3.8/dist-packages (from pycaret) (1.8.2.2)
Requirement already satisfied: textblob in /usr/local/lib/python3.8/dist-packages (from pycaret) (0.15.3)
Collecting pyod
  Downloading pyod-1.0.7.tar.gz (147 kB)
     |████████████████████████████████| 147 kB 9.8 MB/s
Requirement already satisfied: plotly>=4.4.1 in /usr/local/lib/python3.8/dist-packages (from pycaret) (5.5.0)
Collecting spacy<2.4.0
  Downloading spacy-2.3.9-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.0 MB)
     |████████████████████████████████| 5.0 MB 13.8 MB/s
Requirement already satisfied: nltk in /usr/local/lib/python3.8/dist-packages (from pycaret) (3.7)
Collecting mlflow
  Downloading mlflow-2.1.1-py3-none-any.whl (16.7 MB)
     |████████████████████████████████| 16.7 MB 428 kB/s
Collecting imbalanced-learn==0.7.0
  Downloading imbalanced_learn-0.7.0-py3-none-any.whl (167 kB)
     |████████████████████████████████| 167 kB 45.3 MB/s
Requirement already satisfied: yellowbrick>=1.0.1 in /usr/local/lib/python3.8/dist-packages (from pycaret) (1.5)
Collecting scikit-learn==0.23.2
  Downloading scikit_learn-0.23.2-cp38-cp38-manylinux1_x86_64.whl (6.8 MB)
     |████████████████████████████████| 6.8 MB 51.9 MB/s
Collecting mlxtend>=0.17.0
  Downloading mlxtend-0.21.0-py2.py3-none-any.whl (1.3 MB)
     |████████████████████████████████| 1.3 MB 52.9 MB/s
Collecting scikit-plot
  Downloading scikit_plot-0.3.7-py3-none-any.whl (33 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (from pycaret) (1.3.5)
Collecting lightgbm>=2.3.1
  Downloading lightgbm-3.3.3-py3-none-manylinux1_x86_64.whl (2.0 MB)
     |████████████████████████████████| 2.0 MB 59.8 MB/s
Requirement already satisfied: ipywidgets in /usr/local/lib/python3.8/dist-packages (from pycaret) (7.7.1)
Collecting scipy<=1.5.4
  Downloading scipy-1.5.4-cp38-cp38-manylinux1_x86_64.whl (25.8 MB)
     |████████████████████████████████| 25.8 MB 1.3 MB/s
Collecting kmodes>=0.10.1
  Downloading kmodes-0.12.2-py2.py3-none-any.whl (20 kB)
Collecting Boruta
  Downloading Boruta-0.3-py3-none-any.whl (56 kB)
     |████████████████████████████████| 56 kB 4.5 MB/s
Collecting numba<0.55
  Downloading numba-0.54.1-cp38-cp38-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (3.3 MB)
     |████████████████████████████████| 3.3 MB 43.4 MB/s
Collecting umap-learn
  Downloading umap-learn-0.5.3.tar.gz (88 kB)
     |████████████████████████████████| 88 kB 297 kB/s
Collecting pyyaml<6.0.0
  Downloading PyYAML-5.4.1-cp38-cp38-manylinux1_x86_64.whl (662 kB)
     |████████████████████████████████| 662 kB 48.2 MB/s
Requirement already satisfied: seaborn in /usr/local/lib/python3.8/dist-packages (from pycaret) (0.11.2)
Collecting pyLDAvis
  Downloading pyLDAvis-3.3.1.tar.gz (1.7 MB)
     |████████████████████████████████| 1.7 MB 42.4 MB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
Requirement already satisfied: IPython in /usr/local/lib/python3.8/dist-packages (from pycaret) (7.9.0)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.8/dist-packages (from pycaret) (3.2.2)
Requirement already satisfied: joblib in /usr/local/lib/python3.8/dist-packages (from pycaret) (1.2.0)
Requirement already satisfied: gensim<4.0.0 in /usr/local/lib/python3.8/dist-packages (from pycaret) (3.6.0)
Collecting pandas-profiling>=2.8.0
  Downloading pandas_profiling-3.6.1-py2.py3-none-any.whl (328 kB)
     |████████████████████████████████| 328 kB 52.5 MB/s
Requirement already satisfied: numpy>=1.13.3 in /usr/local/lib/python3.8/dist-packages (from imbalanced-learn==0.7.0->pycaret) (1.21.6)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.8/dist-packages (from scikit-learn==0.23.2->pycaret) (3.1.0)
Requirement already satisfied: setuptools>=34.4.1 in /usr/local/lib/python3.8/dist-packages (from cufflinks>=0.17.0->pycaret) (57.4.0)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.8/dist-packages (from cufflinks>=0.17.0->pycaret) (1.15.0)
Requirement already satisfied: colorlover>=0.2.1 in /usr/local/lib/python3.8/dist-packages (from cufflinks>=0.17.0->pycaret) (0.3.0)
Requirement already satisfied: smart-open>=1.2.1 in /usr/local/lib/python3.8/dist-packages (from gensim<4.0.0->pycaret) (6.3.0)
Requirement already satisfied: pygments in /usr/local/lib/python3.8/dist-packages (from IPython->pycaret) (2.6.1)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.8/dist-packages (from IPython->pycaret) (0.7.5)
Requirement already satisfied: prompt-toolkit<2.1.0,>=2.0.0 in /usr/local/lib/python3.8/dist-packages (from IPython->pycaret) (2.0.10)
Collecting jedi>=0.10
  Downloading jedi-0.18.2-py2.py3-none-any.whl (1.6 MB)
     |████████████████████████████████| 1.6 MB 51.3 MB/s
Requirement already satisfied: backcall in /usr/local/lib/python3.8/dist-packages (from IPython->pycaret) (0.2.0)
Requirement already satisfied: decorator in /usr/local/lib/python3.8/dist-packages (from IPython->pycaret) (4.4.2)
Requirement already satisfied: pexpect in /usr/local/lib/python3.8/dist-packages (from IPython->pycaret) (4.8.0)
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.8/dist-packages (from IPython->pycaret) (5.7.1)
Requirement already satisfied: jupyterlab-widgets>=1.0.0 in /usr/local/lib/python3.8/dist-packages (from ipywidgets->pycaret) (3.0.4)
Requirement already satisfied: ipython-genutils~=0.2.0 in /usr/local/lib/python3.8/dist-packages (from ipywidgets->pycaret) (0.2.0)
Requirement already satisfied: widgetsnbextension~=3.6.0 in /usr/local/lib/python3.8/dist-packages (from ipywidgets->pycaret) (3.6.1)
Requirement already satisfied: ipykernel>=4.5.1 in /usr/local/lib/python3.8/dist-packages (from ipywidgets->pycaret) (5.3.4)
Requirement already satisfied: tornado>=4.2 in /usr/local/lib/python3.8/dist-packages (from ipykernel>=4.5.1->ipywidgets->pycaret) (6.0.4)
Requirement already satisfied: jupyter-client in /usr/local/lib/python3.8/dist-packages (from ipykernel>=4.5.1->ipywidgets->pycaret) (6.1.12)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in /usr/local/lib/python3.8/dist-packages (from jedi>=0.10->IPython->pycaret) (0.8.3)
Requirement already satisfied: wheel in /usr/local/lib/python3.8/dist-packages (from lightgbm>=2.3.1->pycaret) (0.38.4)
Collecting mlxtend>=0.17.0
  Downloading mlxtend-0.20.0-py2.py3-none-any.whl (1.3 MB)
     |████████████████████████████████| 1.3 MB 36.0 MB/s
  Downloading mlxtend-0.19.0-py2.py3-none-any.whl (1.3 MB)
     |████████████████████████████████| 1.3 MB 44.8 MB/s
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.8/dist-packages (from matplotlib->pycaret) (3.0.9)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.8/dist-packages (from matplotlib->pycaret) (1.4.4)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.8/dist-packages (from matplotlib->pycaret) (0.11.0)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.8/dist-packages (from matplotlib->pycaret) (2.8.2)
Collecting numpy>=1.13.3
  Downloading numpy-1.20.3-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.4 MB)
     |████████████████████████████████| 15.4 MB 44.0 MB/s
Collecting llvmlite<0.38,>=0.37.0rc1
  Downloading llvmlite-0.37.0-cp38-cp38-manylinux2014_x86_64.whl (26.3 MB)
     |████████████████████████████████| 26.3 MB 65.7 MB/s
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.8/dist-packages (from pandas->pycaret) (2022.6)
Collecting visions[type_image_path]==0.7.5
  Downloading visions-0.7.5-py3-none-any.whl (102 kB)
     |████████████████████████████████| 102 kB 53.5 MB/s
Collecting htmlmin==0.1.12
  Downloading htmlmin-0.1.12.tar.gz (19 kB)
Requirement already satisfied: requests<2.29,>=2.24.0 in /usr/local/lib/python3.8/dist-packages (from pandas-profiling>=2.8.0->pycaret) (2.28.1)
Collecting statsmodels<0.14,>=0.13.2
  Downloading statsmodels-0.13.5-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (9.9 MB)
     |████████████████████████████████| 9.9 MB 46.1 MB/s
Collecting typeguard<2.14,>=2.13.2
  Downloading typeguard-2.13.3-py3-none-any.whl (17 kB)
Requirement already satisfied: jinja2<3.2,>=2.11.1 in /usr/local/lib/python3.8/dist-packages (from pandas-profiling>=2.8.0->pycaret) (2.11.3)
Requirement already satisfied: tqdm<4.65,>=4.48.2 in /usr/local/lib/python3.8/dist-packages (from pandas-profiling>=2.8.0->pycaret) (4.64.1)
Requirement already satisfied: pydantic<1.11,>=1.8.1 in /usr/local/lib/python3.8/dist-packages (from pandas-profiling>=2.8.0->pycaret) (1.10.2)
Collecting multimethod<1.10,>=1.4
  Downloading multimethod-1.9.1-py3-none-any.whl (10 kB)
Collecting phik<0.13,>=0.11.1
  Downloading phik-0.12.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (679 kB)
     |████████████████████████████████| 679 kB 44.7 MB/s
Requirement already satisfied: attrs>=19.3.0 in /usr/local/lib/python3.8/dist-packages (from visions[type_image_path]==0.7.5->pandas-profiling>=2.8.0->pycaret) (22.1.0)
Collecting tangled-up-in-unicode>=0.0.4
  Downloading tangled_up_in_unicode-0.2.0-py3-none-any.whl (4.7 MB)
     |████████████████████████████████| 4.7 MB 54.4 MB/s
Requirement already satisfied: networkx>=2.4 in /usr/local/lib/python3.8/dist-packages (from visions[type_image_path]==0.7.5->pandas-profiling>=2.8.0->pycaret) (2.8.8)
Collecting imagehash
  Downloading ImageHash-4.3.1-py2.py3-none-any.whl (296 kB)
     |████████████████████████████████| 296 kB 47.6 MB/s
Requirement already satisfied: Pillow in /usr/local/lib/python3.8/dist-packages (from visions[type_image_path]==0.7.5->pandas-profiling>=2.8.0->pycaret) (7.1.2)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.8/dist-packages (from jinja2<3.2,>=2.11.1->pandas-profiling>=2.8.0->pycaret) (2.0.1)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.8/dist-packages (from plotly>=4.4.1->pycaret) (8.1.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.8/dist-packages (from prompt-toolkit<2.1.0,>=2.0.0->IPython->pycaret) (0.2.5)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.8/dist-packages (from pydantic<1.11,>=1.8.1->pandas-profiling>=2.8.0->pycaret) (4.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/dist-packages (from requests<2.29,>=2.24.0->pandas-profiling>=2.8.0->pycaret) (2022.12.7)
Requirement already satisfied: charset-normalizer<3,>=2 in /usr/local/lib/python3.8/dist-packages (from requests<2.29,>=2.24.0->pandas-profiling>=2.8.0->pycaret) (2.1.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.8/dist-packages (from requests<2.29,>=2.24.0->pandas-profiling>=2.8.0->pycaret) (1.24.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.8/dist-packages (from requests<2.29,>=2.24.0->pandas-profiling>=2.8.0->pycaret) (2.10)
Requirement already satisfied: wasabi<1.1.0,>=0.4.0 in /usr/local/lib/python3.8/dist-packages (from spacy<2.4.0->pycaret) (0.10.1)
Collecting catalogue<1.1.0,>=0.0.7
  Downloading catalogue-1.0.2-py2.py3-none-any.whl (16 kB)
Collecting thinc<7.5.0,>=7.4.1
  Downloading thinc-7.4.6-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.1 MB)
     |████████████████████████████████| 1.1 MB 44.0 MB/s
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.8/dist-packages (from spacy<2.4.0->pycaret) (3.0.8)
Requirement already satisfied: blis<0.8.0,>=0.4.0 in /usr/local/lib/python3.8/dist-packages (from spacy<2.4.0->pycaret) (0.7.9)
Collecting plac<1.2.0,>=0.9.6
  Downloading plac-1.1.3-py2.py3-none-any.whl (20 kB)
Collecting srsly<1.1.0,>=1.0.2
  Downloading srsly-1.0.6-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (211 kB)
     |████████████████████████████████| 211 kB 73.2 MB/s
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.8/dist-packages (from spacy<2.4.0->pycaret) (2.0.7)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.8/dist-packages (from spacy<2.4.0->pycaret) (1.0.9)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.8/dist-packages (from statsmodels<0.14,>=0.13.2->pandas-profiling>=2.8.0->pycaret) (21.3)
Requirement already satisfied: patsy>=0.5.2 in /usr/local/lib/python3.8/dist-packages (from statsmodels<0.14,>=0.13.2->pandas-profiling>=2.8.0->pycaret) (0.5.3)
Requirement already satisfied: notebook>=4.4.1 in /usr/local/lib/python3.8/dist-packages (from widgetsnbextension~=3.6.0->ipywidgets->pycaret) (5.7.16)
Requirement already satisfied: jupyter-core>=4.4.0 in /usr/local/lib/python3.8/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->pycaret) (5.1.0)
Requirement already satisfied: Send2Trash in /usr/local/lib/python3.8/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->pycaret) (1.8.0)
Requirement already satisfied: nbconvert<6.0 in /usr/local/lib/python3.8/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->pycaret) (5.6.1)
Requirement already satisfied: prometheus-client in /usr/local/lib/python3.8/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->pycaret) (0.15.0)
Requirement already satisfied: pyzmq>=17 in /usr/local/lib/python3.8/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->pycaret) (23.2.1)
Requirement already satisfied: nbformat in /usr/local/lib/python3.8/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->pycaret) (5.7.0)
Requirement already satisfied: terminado>=0.8.1 in /usr/local/lib/python3.8/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->pycaret) (0.13.3)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.8/dist-packages (from jupyter-core>=4.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->pycaret) (2.6.0)
Requirement already satisfied: testpath in /usr/local/lib/python3.8/dist-packages (from nbconvert<6.0->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->pycaret) (0.6.0)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.8/dist-packages (from nbconvert<6.0->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->pycaret) (0.7.1)
Requirement already satisfied: mistune<2,>=0.8.1 in /usr/local/lib/python3.8/dist-packages (from nbconvert<6.0->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->pycaret) (0.8.4)
Requirement already satisfied: entrypoints>=0.2.2 in /usr/local/lib/python3.8/dist-packages (from nbconvert<6.0->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->pycaret) (0.4)
Requirement already satisfied: pandocfilters>=1.4.1 in /usr/local/lib/python3.8/dist-packages (from nbconvert<6.0->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->pycaret) (1.5.0)
Requirement already satisfied: bleach in /usr/local/lib/python3.8/dist-packages (from nbconvert<6.0->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->pycaret) (5.0.1)
Requirement already satisfied: jsonschema>=2.6 in /usr/local/lib/python3.8/dist-packages (from nbformat->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->pycaret) (4.3.3)
Requirement already satisfied: fastjsonschema in /usr/local/lib/python3.8/dist-packages (from nbformat->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->pycaret) (2.16.2)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /usr/local/lib/python3.8/dist-packages (from jsonschema>=2.6->nbformat->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->pycaret) (0.19.2)
Requirement already satisfied: importlib-resources>=1.4.0 in /usr/local/lib/python3.8/dist-packages (from jsonschema>=2.6->nbformat->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->pycaret) (5.10.1)
Requirement already satisfied: zipp>=3.1.0 in /usr/local/lib/python3.8/dist-packages (from importlib-resources>=1.4.0->jsonschema>=2.6->nbformat->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->pycaret) (3.11.0)
Requirement already satisfied: ptyprocess in /usr/local/lib/python3.8/dist-packages (from terminado>=0.8.1->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->pycaret) (0.7.0)
Collecting yellowbrick>=1.0.1
  Downloading yellowbrick-1.4-py3-none-any.whl (274 kB)
     |████████████████████████████████| 274 kB 78.2 MB/s
  Downloading yellowbrick-1.3.post1-py3-none-any.whl (271 kB)
     |████████████████████████████████| 271 kB 70.1 MB/s
Collecting numpy>=1.13.3
  Downloading numpy-1.19.5-cp38-cp38-manylinux2010_x86_64.whl (14.9 MB)
     |████████████████████████████████| 14.9 MB 58.7 MB/s
Requirement already satisfied: webencodings in /usr/local/lib/python3.8/dist-packages (from bleach->nbconvert<6.0->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->pycaret) (0.5.1)
Requirement already satisfied: PyWavelets in /usr/local/lib/python3.8/dist-packages (from imagehash->visions[type_image_path]==0.7.5->pandas-profiling>=2.8.0->pycaret) (1.4.1)
Requirement already satisfied: cloudpickle<3 in /usr/local/lib/python3.8/dist-packages (from mlflow->pycaret) (1.5.0)
Collecting docker<7,>=4.0.0
  Downloading docker-6.0.1-py3-none-any.whl (147 kB)
     |████████████████████████████████| 147 kB 60.7 MB/s
Requirement already satisfied: markdown<4,>=3.3 in /usr/local/lib/python3.8/dist-packages (from mlflow->pycaret) (3.4.1)
Requirement already satisfied: importlib-metadata!=4.7.0,<6,>=3.7.0 in /usr/local/lib/python3.8/dist-packages (from mlflow->pycaret) (5.1.0)
Collecting alembic<2
  Downloading alembic-1.9.1-py3-none-any.whl (210 kB)
     |████████████████████████████████| 210 kB 45.4 MB/s
Requirement already satisfied: pyarrow<11,>=4.0.0 in /usr/local/lib/python3.8/dist-packages (from mlflow->pycaret) (9.0.0)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.8/dist-packages (from mlflow->pycaret) (7.1.2)
Requirement already satisfied: Flask<3 in /usr/local/lib/python3.8/dist-packages (from mlflow->pycaret) (1.1.4)
Collecting databricks-cli<1,>=0.8.7
  Downloading databricks-cli-0.17.4.tar.gz (82 kB)
     |████████████████████████████████| 82 kB 481 kB/s
Collecting querystring-parser<2
  Downloading querystring_parser-1.2.4-py2.py3-none-any.whl (7.9 kB)
Collecting gunicorn<21
  Downloading gunicorn-20.1.0-py3-none-any.whl (79 kB)
     |████████████████████████████████| 79 kB 8.3 MB/s
Collecting gitpython<4,>=2.1.0
  Downloading GitPython-3.1.30-py3-none-any.whl (184 kB)
     |████████████████████████████████| 184 kB 58.8 MB/s
Requirement already satisfied: sqlalchemy<2,>=1.4.0 in /usr/local/lib/python3.8/dist-packages (from mlflow->pycaret) (1.4.45)
Requirement already satisfied: sqlparse<1,>=0.4.0 in /usr/local/lib/python3.8/dist-packages (from mlflow->pycaret) (0.4.3)
Requirement already satisfied: protobuf<5,>=3.12.0 in /usr/local/lib/python3.8/dist-packages (from mlflow->pycaret) (3.19.6)
Collecting shap<1,>=0.40
  Downloading shap-0.41.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (575 kB)
     |████████████████████████████████| 575 kB 50.7 MB/s
Collecting Mako
  Downloading Mako-1.2.4-py3-none-any.whl (78 kB)
     |████████████████████████████████| 78 kB 7.5 MB/s
Collecting pyjwt>=1.7.0
  Downloading PyJWT-2.6.0-py3-none-any.whl (20 kB)
Requirement already satisfied: oauthlib>=3.1.0 in /usr/local/lib/python3.8/dist-packages (from databricks-cli<1,>=0.8.7->mlflow->pycaret) (3.2.2)